### ISSUE TITLE
Issue about dataset

### ISSUE THREAD

**Issue by icmpnorequest** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#1]
Hi yingtao,

Could you please upload the data file like `gowalla_POI.csv`and `gowalla.csv`？

**Comment by yingtaoluo** [comment]
I have been tied up with some other papers at hand. Sorry for the delay. The dataset will come out soon. Probably in a week or so. Email me again at any time if it fails to come out in a week. Thanks.

**Comment by yingtaoluo** [comment]
Dataset has been updated! 

To whom it may concern,
It is a formal apology from Yingtao that I uploaded the wrong codes to implement STAN: Spatio-Temporal Attention Network last month. These wrong codes (if you download before 3/18) are trial-version codes and are not the ones we use to report performance. I have corrected this mistake and please do re-download the codes if you are using the wrong codes. Again, I am sorry for my negligence. 
Hope you have a nice day. 

Sincerely,
Yingtao Luo

**Comment by yingtaoluo** [comment]
Data is already uploaded. Gowalla is too big so I am figuring out a safe way to share the data.

**Comment by icmpnorequest** [comment]
Thanks for your guidance and patience, Yingtao and I will close this issue.
Best regards.

**Comment by H-Yin** [comment]
> 
> 
> Data is already uploaded. Gowalla is too big so I am figuring out a safe way to share the data.

Where can i download the preprocessed dataset of Gowalla, i.e. Gowalla.npy and Gowalla_POI.npy
