### ISSUE TITLE
running time is unacceptable

### ISSUE THREAD

**Issue by plzhai** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#14]
Hi, the idea in this article is somewhat interesting. 

however, the running time is unacceptable absolutely, even on the provided toy data.

why using batch-size 1 and mask-len from 1 to len  in the experiment? This setting helps better performance?

**Comment by yingtaoluo** [comment]
Yes, you are correct. Perhaps it is better to revise the codes. I also state this problem in the readme file, but could not find time to rewrite it. Next year's summer break I will see what I can do. Sorry.

**Comment by yingtaoluo** [comment]
Yes, you are correct. Perhaps it is better to revise the codes. I also
state this problem in the readme file, but could not find time to rewrite
it. Next year's summer break I will see what I can do. Sorry.

**Comment by plzhai** [comment]
> 

the reported baseline results in your paper are reproduced by yourselves?

they are also evaluated on all the locations of the dataset? I remember that GeoSAN evaluates their results on a sampled small set of all the locations.

**Comment by zhzfight** [comment]
hi, have you run STAN on other datasets and how did it work? thank you for reply

**Comment by yingtaoluo** [comment]
> Hi, the idea in this article is somewhat interesting.
> 
> however, the running time is unacceptable absolutely, even on the provided toy data.
> 
> why using batch-size 1 and mask-len from 1 to len in the experiment? This setting helps better performance?

Thanks. Sorry if I did not check the repo regularly. The setting is not standard, and I personally do not recommend evaluating a POI model based on our own setting... The only reason we did so was precisely because of the limitations due to computational resources.

**Comment by yingtaoluo** [comment]
> hi, have you run STAN on other datasets and how did it work? thank you for reply



> hi, have you run STAN on other datasets and how did it work? thank you for reply

We only tested on the four datasets listed in the paper.
