### ISSUE TITLE
The invalid dataset link for the SIN dataset fixed

### ISSUE THREAD

**Issue by Charlie1994** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#15]
Hi there,
This is a note that I just found the correct link for the dataset SIN (which was originally [https://www.ntu.edu.sg/home/gaocong/data/poidata.zip](https://www.ntu.edu.sg/home/gaocong/data/poidata.zip)). The reason to the invalid url issue is that NTU changed the domain name of each staff member homepage to personal.ntu.edu.sg. However, the directory structure has not been changed. So you can download the SIN dataset from [https://personal.ntu.edu.sg/gaocong/data/poidata.zip](https://personal.ntu.edu.sg/gaocong/data/poidata.zip).

You can close this issue once you update the README.md.

Thanks
Charles

**Comment by yingtaoluo** [comment]
Thanks a lot.
