### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by Wsheng19** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#16]
Hi, I am very interested in your work, but I do have some questions about the code. First, I wonder how the data is preprocessed. The data I downloaded from the site, such as Gowalla, the number of users and locations is different from what you presented in your paper. Secondly, I do not quite understand the division of data set, since your approach is different from previous related work, so I do not know how to compare with other methods. Thirdly, I was puzzled for a long time by the fact that I would get an error if I dialed a large number of batch size.

**Comment by yingtaoluo** [comment]
Thank you. There may be similar questions asked before. For batch size, I am deeply sorry for causing the trouble you encounter. You may have to rewrite the codes if you prefer to increase batch size... Sorry for that.

**Comment by Wsheng19** [comment]
> 

Hi, I am still wondering how the data is preprocessed, such as filtering users and locations. I don't see the solution to this question anywhere else. I appreciate it if you could do my a favor.

**Comment by datacheff** [comment]
Hello, I am also curious about data preprocessing. I've tried data preprocessing in various ways, but it doesn't work with data that has similar tendencies to the numbers of users and poi in the dataset table. Thank you very much for your reply.
