### ISSUE TITLE
How to reproduce the recall values reported in the paper

### ISSUE THREAD

**Issue by yeliudev** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#18]
Hi @yingtaoluo. Thanks for your great work. I notice that your code only calculates ACC rather than Recall for evaluation. May I ask that how can I obtain the Recall values as reported in your paper? Thanks!

**Comment by yingtaoluo** [comment]
My apologies that although the evaluation is named "ACC", it is actually Recall. Sorry for the misleading description.

**Comment by yeliudev** [comment]
I see. Thanks for your reply!
