### ISSUE TITLE
Which test accuracy score you report from all the epoch?

### ISSUE THREAD

**Issue by Rajjat** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#19]
Hello,
I am using your code. It was executed for all the 100 epochs with validation accuracy and test accuracy scores displayed for each epoch. but I have one question:- Which test score do you report in the final. Is it the maximum test score out of all the epochs?

**Comment by yingtaoluo** [comment]
Hi,
We select the epoch where we have the maximum validation score and record the test score of this epoch.

**Comment by Rajjat** [comment]
Thanks for your reply!
