### ISSUE TITLE
Can you provide a dataset?

### ISSUE THREAD

**Issue by leehommlee** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#2]

**Comment by yingtaoluo** [comment]
I have been tied up with some other papers at hand. Sorry for the delay. The dataset will come out soon. If you are in a hurry for the dataset, please do not hesitate to comment here again to remind me if it does not come out in a week. Thanks.

**Comment by yingtaoluo** [comment]
Dataset has been updated!

To whom it may concern,
It is a formal apology from Yingtao that I uploaded the wrong codes to implement STAN: Spatio-Temporal Attention Network last month. These wrong codes (if you download before 3/18) are trial-version codes and are not the ones we use to report performance. I have corrected this mistake and please do re-download the codes if you are using the wrong codes. Again, I am sorry for my negligence. 
Hope you have a nice day. 

Sincerely,
Yingtao Luo

**Comment by yingtaoluo** [comment]
Data is already uploaded. Gowalla is too big so I am figuring out a safe way to share the data.

**Comment by zhouchen197576** [comment]
Hello, author! I have a few questions to ask you.
According to the link you provided, the second link is invalid. The data format downloaded from the first and third links is TXT, while the format in the code is pkl. I tried to change it to TXT directly, but it didn't succeed. The code would report an error. What should be done?
Finally, I hope you can provide the data set directly. You can consider using cloud disk to store it, and then provide the download link. Thank you very much.

**Comment by zhouchen197576** [comment]
Hello, Yingtao Luo! 
According to the link you provided, the second link is invalid. The data format downloaded from the first and third links is TXT, while the format in the code is pkl. I tried to change it to TXT directly, but it didn't succeed. The code would report an error. What should be done?
Finally, I hope you can directly provide the data set, you can consider using Baidu cloud disk storage, and then provide the download link. Thank you very much.

**Comment by yingtaoluo** [comment]
I am curious why you get into this problem at all. The raw data is clearly
not preprocessed. You should preprocess it at first.

Regards,
Yingtao
