### ISSUE TITLE
where can I find the topk location in the model(.pth)?

### ISSUE THREAD

**Issue by lixin716** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#20]
hello,
I am reading your code,nice work! and I do not know how to get the topk locations in the model.

And I also want to know the meaning of the state_dict,like MultiEmbed.emb_t.weight,MultiEmbed.emb_su.weight,Attn.emb_loc.weight and so on.

Thanks,

**Comment by lixin716** [comment]
@yingtaoluo

**Comment by yingtaoluo** [comment]
These are pytorch specified languages. You can search for topk function of numpy or torch. weight here means learnable parameters...
