### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by dejuzhang** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#21]
你好，关于代码中的data实例，NYC.py的维度是<147938,3>，147938我明白是check-in的数量，第二个维度中的3维数据是什么意思呢？谢谢您，如果您能回答，我会很感激

**Comment by yingtaoluo** [comment]
So sorry for delayed response. There should be location_id, longitude and latitude for poi file, and user_id, location_id, time for data file.
