### ISSUE TITLE
Can you please explain your trajectory encoding process?

### ISSUE THREAD

**Issue by princeagarwal12** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#3]
Hello! Thanks for sharing the dataset and the resources. Can you please explain a bit in detail your data encoding method? Some of the approaches have created the location embeddings using skip-gram like approaches. I can see that you've used transition matrices and checkin sequences and then created embeddings but I am unable to understand what you are doing after that and how you're feeding it to attention laters? It would be great if you could please explain this a bit.

**Comment by yingtaoluo** [comment]
Hi, Prince.

Thanks for asking this. Pre-training of embedding is an effective approach
and can further improve the performance for sure. Unfortunately, the focus
and contribution of this paper are not on embedding pre-training, and
pretraining is not used in baselines, so we do not use it in our paper.
Nevertheless, it will be a contribution if you conceive new ideas to
improve embedding efficiency.

Best,
Yingtao

**Comment by princeagarwal12** [comment]
Thanks Yingtao, for your reply.

**Comment by zhouchen197576** [comment]
Hi,yingtaoluo.
Thank you for your sharing and previous answers. I have already generated the "nyc_data.pkl" file with the provided "nyc.py" and "nyc_poi.py" file and started the training successfully.
I looked at the code and found that the .npy file was processed by the .csv file in the "load.py". Firstly, data preprocessing is completed in the "load.py" file to get the .pkl file, and then model training is carried out through the "train.py" file to get the results. 
But I don't understand how you can process raw data (such as Gowalla_edges. txt , gowalla_totalcheckers.txt or dataset_TSMC2014_TKY.txt) from file format .txt into .csv files? Can you explain it in detail? Thank you very much.

**Comment by yingtaoluo** [comment]
Hi Zhouchen,

The process from txt to csv is conducted by the second & correspondent
author of the paper, Prof. Qiang Liu. You can ask him if you really
need the info. It is a trivial form problem I think.
Regarding the invalid link, I also have no idea why it is not working any
longer. Before we submit the paper, it was working just fine.

Kinds regards,
Yingtao

**Comment by ZQSong1997** [comment]
谢谢，请允许我直接用中文提问吧。我其实知道怎么样从txt转换为csv，这很简单。
我真正疑惑的是因为我在你们的代码里面没发现如何将从网站下载得到的txt原始数据处理为csv这一步骤。所以我不确定是否可以直接先将Gowalla_edges. txt 和gowalla_totalcheckers.txt这样的文件改为csv后，再直接让load.py模块进行处理。但我感觉这种方式是不行的，所以想请问你们是如何将原始的txt格式的dataset变成所需要的npy/csv文件？
简单的说，就是想知道你们如何将Gowalla_edges. txt和gowalla_totalcheckers.txt处理为gowalla_POI.csv和gowalla.csv这两个代码中所依赖的文件？

**Comment by yingtaoluo** [comment]
Hi,

Like I said before, please ask the corresponding author for this. I am not
in charge of the preprocessing. This is collaboration work.
It is perfectly fine to transform txt to csv. You only need to define the
DataFrame you need (which we have defined in the problem description
section) and discard irrelevant features.
I am not sure I follow. This should not be a problem to my best knowledge.
If you have other questions, feel free to email me.

Best,
Yingtao
