### ISSUE TITLE
Call for the NYC dataset

### ISSUE THREAD

**Issue by swiftCC** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#30]
hello, the link below can't be open. Can u send me the origin NYC dataset that you have used in the experiment? thanks!

**Comment by yingtaoluo** [comment]
Thanks. Please see the data folder of this repo.

**Comment by swiftCC** [comment]
> 谢谢。请参阅此存储库的数据文件夹。

Yes, I mean that how to get the two npy files in the data folder like NYC when I want to train other dataset like Gowalla? thanks!

**Comment by Iscodebrid** [comment]
> Thanks. Please see the data folder of this repo.

Hello, may I ask if you can share the other two datasets (.pkl format) besides the NYC dataset? Thanks

**Comment by yingtaoluo** [comment]
I directly re-use the data used by the STRNN paper in 2016, and I also do not have the code to get the csv file. The npy file is the same to the csv file. The pkl file is too large and I suggest using the load.py to directly generate from the original data.

**Comment by Iscodebrid** [comment]
> I directly re-use the data used by the STRNN paper in 2016, and I also do not have the code to get the csv file. The npy file is the same to the csv file. The pkl file is too large and I suggest using the load.py to directly generate from the original data.

Thank you for your reply! I would like to ask you if you have any suggestions on applying this model to a federated learning framework?

**Comment by yingtaoluo** [comment]
> > I directly re-use the data used by the STRNN paper in 2016, and I also do not have the code to get the csv file. The npy file is the same to the csv file. The pkl file is too large and I suggest using the load.py to directly generate from the original data.
> 
> Thank you for your reply! I would like to ask you if you have any suggestions on applying this model to a federated learning framework?

Thank you for the feedback. I am not an expert in federated learning, but many models can be extended to a federated learning version. I could only guess that if there is a very suitable problem, such as if different institutions have different geo data and want to protect their own data privacy, it will make a lot of sense to do so.

**Comment by Iscodebrid** [comment]
Thank you for your reply, it will help me a lot！
