### ISSUE TITLE
Using model

### ISSUE THREAD

**Issue by pial98** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#33]
As this model is for generating future POIs , can it be used for showing next POIs if changes are made to inference method?

**Comment by yingtaoluo** [comment]
I am not sure that I understand your question. Do you mind elaborating it again?

**Comment by pial98** [comment]
Hello,
Firstly I want to know how this model generating test accuracy and
validation accuracy as there are no information about that.
Secondly , I want to know that if this model can be modified so that I can
know where a user will go in the next visit by analyzing that user's past
visits.

**Comment by yingtaoluo** [comment]
The code has surely covered the test and validation eval. See lines 144 and 147 in train.py. 

STAN is already predicting the next visit by analyzing user's past visits. I am still confused. Are you suggesting you want to directly know the next visit at any potential geographical coordinates? That might be possible, but will be hard.

**Comment by yingtaoluo** [comment]
If there are other concerns, feel free to reopen the issue.

**Comment by pial98** [comment]
Hello,

If I want to use your model in a tourism based website then how can I do it?
As after running your code I only get to know about the training and
validation accuracy.I am constantly trying to change the inference method
of the train.py but nothing is working as I am expecting.
