### ISSUE TITLE
Input data (line #211 @ train.py)

### ISSUE THREAD

**Issue by eoameen** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#34]
Hi @yingtaoluo,

I went through all issues open and closed and couldn't find an answer to the following question:

What is the format of the data used by train.py at line #211?

The only data you have available are NYC.pkl and NYC_POI.pkl and neither of them is the actual trajectory data, right? Why don't you upload trajectory data (part of it is ok) so that we can run your code without difficulty?

If you don't want to share the data, could you explain the actual format the code expects at the line #211 in train.py?

Thanks

**Comment by yingtaoluo** [comment]
You can directly download data from the links I provided, and there would be copyright concerns to share all the data in my own way. NYC.pkl is the trajectory data. You can use load.py to process the data.

**Comment by eoameen** [comment]
Thank you for the quick reply!
I ran load.py and I'm getting "segmentation fault: 11" halfway through the process. I'm getting the same error on three different platforms: 1x Mac and 2x Linux with 128GB of ram. Have you faced this error before?

UPDATE:
I finally managed to resolve the issue. Thank you!

**Comment by eoameen** [comment]
@yingtaoluo please ignore the message above. I managed to successfully run it! Issue resolved
