### ISSUE TITLE
Time encoding in NYC.npy

### ISSUE THREAD

**Issue by eoameen** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#35]
Hi again,

I read #8 but I'm still not sure how the time is encoded into an integer from a timestamp. Could you elaborate?

Background:
I'm trying to run your algorithm on my own pre-processed data (Using load.py) and I'm not sure how to encode check-in time as you did.

Thank you in advance

**Comment by yingtaoluo** [comment]
Yes, basically they record in seconds, and I map them into minutes. You can also try to map them into hours. So time is an integer from the beginning if you directly just map the absolute time to seconds.
