### ISSUE TITLE
Can you explain the setting of experiments in your paper?

### ISSUE THREAD

**Issue by JBK12** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#4]
Hello! I'm very interested in your work. I am curious about the number of candidates and how to generate candidates. Can you explain more about the candidate in the experiment of your paper?

**Comment by yingtaoluo** [comment]
Hello! The number of candidate locations is determined by the number of
locations that exist in the dataset. It varies with different datasets.

**Comment by yingtaoluo** [comment]
All locations that exist in the dataset are considered as candidates.

**Comment by coolcoolcat** [comment]
Is your email yl3851@uw.edu? I have sent you an email to ask some questions, but you may not have received it due to domestic network restrictions. If not, I will apply for an overseas email address and try again.

**Comment by yingtaoluo** [comment]
No worries. The email spam causes the delay but I did receive your message.
Let's talk via email instead of email. Thanks.
