### ISSUE TITLE
Question regarding STAN_WIN and dataset

### ISSUE THREAD

**Issue by rbhatia46** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#5]
Hi, nice work!

I have two questions, first one is that where is the STAN_WIN library which you are importing, I can't find any py file for the same.

Secondly, I wanted to understand the dataset included in the repo. I understood that the NYC_POI.npy contains the POI ID, and the latitude, longitude.

What does each column in NYC.npy mean ?

**Comment by yingtaoluo** [comment]
Hi Rahul,

Thank you for asking this question. Many people have the same doubt so I
will add it to the FAQ.

STAN_WIN: I will edit this out to make you run it without modifying any
codes.
NYC.npy contains a column of [user id, check-in location id, time in
seconds]'s.

Best,
Yingtao

**Comment by rbhatia46** [comment]
When you say time in seconds, do you mean duration spent at that particular POI or something else, sorry I am confused with that part, can you please confirm ?

Thanks

**Comment by yingtaoluo** [comment]
The absolute time in the universe, unrelated to any particular user or
location. We let it start from 0 to the max_time.

**Comment by rbhatia46** [comment]
Understood, thanks for the clarification.
