### ISSUE TITLE
Question about "traj[:, :, 2]"

### ISSUE THREAD

**Issue by pshijie** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#7]
Hi，I'm very interested in your work. But I have question about this line of code:"(traj[:, :, 2]-1) % hours + 1". Is this variable in seconds or hours?
Thanks!

**Comment by yingtaoluo** [comment]
It will help me greatly if you can be more precise about which line. If you
mean line 104 in layer.py, then this is in hours. I explain in my paper
that we divide time into 24*7 hours to consider weekly periodicity.

**Comment by pshijie** [comment]
Thanks for the clarification.
