### ISSUE TITLE
Can you explain how to generate  the file NYC.npy ?

### ISSUE THREAD

**Issue by Davidchenw** [yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation#8]
Can you explain how to encode the time in hours in the file NYC.npy？

**Comment by yingtaoluo** [comment]
Oh, we basically only record the time information of the original dataset down to the detail level of minutes and then /60 to get the int value as hours.

**Comment by 979955** [comment]
Hello, I want to run with my own data set, but I am not clear about the data in your NYC_data.pkl file
